from playwright.sync_api import sync_playwright

def verify_app():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()

        # Navigate to the local server
        page.goto("http://localhost:8080")

        # Wait for the canvas to be present (generated by Three.js)
        try:
            page.wait_for_selector("canvas", timeout=10000)
            print("Canvas found.")

            # Wait a bit for particles to generate and render
            page.wait_for_timeout(2000)

            # Take a screenshot
            screenshot_path = "verification/screenshot.png"
            page.screenshot(path=screenshot_path)
            print(f"Screenshot saved to {screenshot_path}")

        except Exception as e:
            print(f"Error: {e}")

        finally:
            browser.close()

if __name__ == "__main__":
    verify_app()
